# Generated by Django 5.1.2 on 2025-02-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swachathapp', '0006_remove_order_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
