# Generated by Django 5.1.2 on 2025-02-20 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swachathapp', '0007_customuser_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_number',
            new_name='phonenumber',
        ),
    ]
