# Generated by Django 5.1.2 on 2025-02-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swachathapp', '0002_alter_vegetable_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(default='Not Provided'),
            preserve_default=False,
        ),
    ]
