# Generated by Django 5.1.2 on 2025-02-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swachathapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetable',
            name='weight',
            field=models.CharField(blank=True, default=100, max_length=50),
            preserve_default=False,
        ),
    ]
