# Generated by Django 5.1.2 on 2025-02-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swachathapp', '0004_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(),
        ),
    ]
